### ISSUE TITLE
why delete?

### ISSUE THREAD

**Issue by yathit** [pstjvn/pstj-closure#14]
Why will you use `delete` in stead of setting `null` in [ScrollArea](https://github.com/pstjvn/pstj-closure/blob/master/ui/scrollarea.js#L187) according to [Google JS guide line](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml#delete)?

**Comment by pstjvn** [comment]
Its very old code, written before the update of the guidelines, delete was regularly used in closure library back then and I just dont have the time to go over all of the code to fix it.
